// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOiZqAS_M8Fp9GQQm7R2mCu3TF6KrCNSI',
    appId: '1:932105234815:web:4a55f1da40ebe6667c924a',
    messagingSenderId: '932105234815',
    projectId: 'flutter-chat-app-1ced0',
    authDomain: 'flutter-chat-app-1ced0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1ced0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwn0pCL8je-AgR688-adU2uNB0VAVp37c',
    appId: '1:932105234815:android:cf8ae701380b1f947c924a',
    messagingSenderId: '932105234815',
    projectId: 'flutter-chat-app-1ced0',
    storageBucket: 'flutter-chat-app-1ced0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl1FQQhcyZIlfhwXpbmnTLWAgpLPLM6h4',
    appId: '1:932105234815:ios:6ecf11dfd6f418487c924a',
    messagingSenderId: '932105234815',
    projectId: 'flutter-chat-app-1ced0',
    storageBucket: 'flutter-chat-app-1ced0.appspot.com',
    iosClientId:
        '932105234815-7jb37r51taelqsu312d8mhfnh56kq2f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl1FQQhcyZIlfhwXpbmnTLWAgpLPLM6h4',
    appId: '1:932105234815:ios:5ceefa9bf650b8c57c924a',
    messagingSenderId: '932105234815',
    projectId: 'flutter-chat-app-1ced0',
    storageBucket: 'flutter-chat-app-1ced0.appspot.com',
    iosClientId:
        '932105234815-69nefolpa7b48fob9q7l39lotonmduf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
